query{
  directories{
    id
    name
    slug
    readableRoot
    writableRoot
    readableUser
    writableUser
    readableGuest
    writableGuest
    user{
      id
      name
      role{
        id
        name
      }
    }
    belongsTo{
      id
      name
      slug
    }
  }
}