query Directory($input: String!){
  directory: directoryById(id: $input){
     id
    name
    slug
    readableRoot
    writableRoot
    readableUser
    writableUser
    readableGuest
    writableGuest
    user{
      id
      name
      role{
        id
        name
      }
    }
    belongsTo{
      id
      name
      slug
    }
  }
}